apiVersion: apps/v1          # Kubernetes API 버전
kind: Deployment             # 리소스 타입: 애플리케이션 배포 관리
metadata:
  name: echo-server          # Deployment 이름
  namespace: default         # 네임스페이스 (기본값)
  labels:
    app: echo-server         # Deployment에 붙는 라벨
spec:
  selector:
    matchLabels:
      app: echo-server       # 이 Deployment가 관리할 Pod를 선택하는 라벨
  replicas: 1              # 실행할 Pod 개수
  template:
    metadata:
      labels:
        app: echo-server       # Pod에 붙을 라벨 (selector와 일치해야 함)
    spec:
      containers:
      - name: main             # 컨테이너 이름
        image: k8s.gcr.io/echoserver:1.6  # 사용할 Docker 이미지
        ports:
        - containerPort: 8080  # 컨테이너가 노출하는 포트
        resources:             # 리소스 제한/요청
          requests:            # 최소 보장 리소스
            cpu: 100m          # 0.1 CPU 코어
            memory: 100Mi      # 100 메가바이트 메모리
          limits:              # 최대 사용 리소스
            cpu: 100m          # 0.1 CPU 코어
            memory: 100Mi      # 100 메가바이트 메모리
---
apiVersion: v1
kind: Service                # 리소스 타입: 네트워크 서비스
metadata:
  name: echo-server          # Service 이름
  namespace: default         # 네임스페이스
spec:
  type: NodePort             # 서비스 타입 (클러스터 외부 접근 가능)
  selector:
    app: echo-server         # 트래픽을 전달할 Pod 선택 라벨
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080         # 컨테이너의 실제 포트
    nodePort: 30950
  # HTTPS 포트는 echo-server가 지원하지 않으므로 제거하거나
  # 필요하다면 별도의 TLS 종료 프록시 사용